baseURL = "https://todaypurpose.com/"
theme = "hyde"
title = "Today purpose"
publishDir = "docs"
canonifyurls = true

[params]
  description = "Your life, your time"
  themeColor = "theme-base-09"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Today Purpose"

# Menu Configuration
[[menu.main]]
  weight = 2
  identifier = "categories"
  name = "Categories"
  url = "/categories"
[[menu.main]]
  weight = 3
  identifier = "tags"
  name = "Tags"
  url = "/tags"
[[menu.main]]
  weight = 4
  identifier = "archives"
  name = "Archives"
  url = "/archives"