baseURL = "https://todaypurpose.com/"
theme = "hyde"
title = "Today Purpose"
publishDir = "docs"
canonifyurls = true
googleAnalytics = "G-V841DEQ6NN"
summaryLength = 70
disqusShortname = "today-purpose"

[params]
  description = " "
  # themeColor = "theme-base-0d"
  themeColor = "theme-base-09"
  layoutReverse = false
  copyright = " "

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Today Purpose"

# Menu Configuration
[[menu.main]]
  weight = 2
  identifier = "categories"
  name = "Twitter"
  url = "https://twitter.com/today_purpose"
